# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: async.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'async.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61sync.proto\x12\x05\x61sync\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"?\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t2H\n\x0c\x41syncService\x12\x38\n\x0bProcessTask\x12\x12.async.TaskRequest\x1a\x13.async.TaskResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'async_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=22
  _globals['_TASKREQUEST']._serialized_end=52
  _globals['_TASKRESPONSE']._serialized_start=54
  _globals['_TASKRESPONSE']._serialized_end=117
  _globals['_ASYNCSERVICE']._serialized_start=119
  _globals['_ASYNCSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
